# Generated by Django 5.2.5 on 2025-08-26 09:23

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('1', 'مدیر کل'), ('2', 'مدیر'), ('3', 'کارمند')], default='1', max_length=10, verbose_name='سطح کاربر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_employees', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('start_date', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_date', models.CharField(max_length=10, verbose_name='تاریخ پایان')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('sensitivity', models.CharField(choices=[('1', 'کم'), ('2', 'متوسط'), ('3', 'زیاد')], max_length=5, verbose_name='حساسیت')),
                ('is_completed', models.BooleanField(default=False, verbose_name='وضعیت انجام')),
                ('visibility', models.BooleanField(verbose_name='وضعیت نمایش')),
                ('creater', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creater_activities', to=settings.AUTH_USER_MODEL, verbose_name='خالق')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت ها',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(related_name='users_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربران تیکت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('conversation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='app.conversation', verbose_name='تیکت')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='09123456789', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='شماره تلفن همراه باید 11 رقمی و با 0 اول باشد.')], verbose_name='تلفن همراه')),
                ('address', models.CharField(max_length=700, verbose_name='آدرس')),
                ('phone_number_1', models.CharField(help_text='09123456789', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='شماره تلفن همراه باید 11 رقمی و با 0 اول باشد.')], verbose_name='تلفن همراه بستگان')),
                ('phone_number_2', models.CharField(help_text='09123456789', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='شماره تلفن همراه باید 11 رقمی و با 0 اول باشد.')], verbose_name='تلفن همراه بستگان')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[app.models.validate_national_code], verbose_name='کد ملی')),
                ('birthdate', models.CharField(max_length=10, verbose_name='تاریخ تولد')),
                ('national_card', models.ImageField(upload_to='national_card/', verbose_name='تصویر کارت ملی')),
                ('guarantee', models.ImageField(blank=True, null=True, upload_to='guarantee/', verbose_name='تصویر ضمانت نامه')),
                ('status', models.CharField(choices=[('1', 'در انتظار بررسی'), ('2', 'تایید شده'), ('3', 'رد شده')], default='1', max_length=20, verbose_name='وضعیت')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
