# Generated by Django 5.2.5 on 2025-08-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='message/', verbose_name='فایل ضمیمه'),
        ),
    ]
